### ISSUE TITLE
large bed file loading error

### ISSUE THREAD

**Issue by sa501428** [aidenlab/Juicebox#339]
On Frankenstein with 20GB RAM initialization

INFO [2016-03-02 14:29:41,491]  [GenomeManager.java:130] [pool-1-thread-1]  Loading genome: http://igvdata.broadinstitute.org/genomes/mm9.genome
INFO [2016-03-02 14:29:41,512]  [HttpUtils.java:1050] [pool-1-thread-1]  Downloading http://igvdata.broadinstitute.org/genomes/mm9.genome to /home/mshamim/igv/genomes/mm9.genome
INFO [2016-03-02 14:29:42,839]  [HttpUtils.java:1091] [pool-1-thread-1]  Download complete.  Total bytes downloaded = 2918493
INFO [2016-03-02 14:29:43,679]  [GenomeManager.java:174] [pool-1-thread-1]  Genome loaded.  id= mm9
ERROR [2016-03-02 14:29:43,687]  [HiCTrackManager.java:185] [pool-1-thread-1]  Error loading track: /media/mshamim/Lavery_Backup/ZoghbiLab/HiC_Feb2016/RNA_Seq/Wooi/bedfile1/file1_chr2.bed
java.lang.RuntimeException: IGV has not been initialized.  Must call createInstance(Frame) first
    at org.broad.igv.ui.IGV.getInstance(IGV.java:172)
    at org.broad.igv.ui.IGV.getMainFrame(IGV.java:199)
    at org.broad.igv.track.TribbleFeatureSource.createIndex(TribbleFeatureSource.java:107)
    at org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:77)
    at org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:60)
    at juicebox.track.HiCTrackManager.loadTribbleFile(HiCTrackManager.java:308)
    at juicebox.track.HiCTrackManager.loadTrack(HiCTrackManager.java:179)
    at juicebox.track.HiCTrackManager.unsafeLoad(HiCTrackManager.java:104)
    at juicebox.track.HiCTrackManager.access$200(HiCTrackManager.java:52)
    at juicebox.track.HiCTrackManager$2.run(HiCTrackManager.java:95)
    at juicebox.MainWindow$3.call(MainWindow.java:189)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by sa501428** [comment]
bigbed should be used for big bed files
