### ISSUE TITLE
HICCUPS report Exception in thread "pool-2-thread-1" java.lang.ArrayIndexOutOfBoundsException: 5980

### ISSUE THREAD

**Issue by caochch** [aidenlab/Juicebox#901]
Using the following configurations for HiCCUPS:
Config res: 5 peak: 5 window: 10 fdr: 10% radius: 30
WARNING - You are using the CPU version of HiCCUPS.
The GPU version of HiCCUPS is the official version and has been tested extensively.
The CPU version only searches for loops within 8MB (by default) of the diagonal and is still experimental.
Using 1 CPU thread(s)
Unable to assess map sparsity; continuing with HiCCUPS
Running HiCCUPS for resolution 5
4%
8%
13%
Exception in thread "pool-2-thread-1" java.lang.ArrayIndexOutOfBoundsException: 5980
        at juicebox.tools.utils.juicer.hiccups.GPUController.runCPUVersion(GPUController.java:384)
        at juicebox.tools.utils.juicer.hiccups.GPUController.process(GPUController.java:141)
        at juicebox.tools.clt.juicer.HiCCUPS.runCoreCodeForHiCCUPS(HiCCUPS.java:521)
        at juicebox.tools.clt.juicer.HiCCUPS.access$200(HiCCUPS.java:158)
        at juicebox.tools.clt.juicer.HiCCUPS$1.run(HiCCUPS.java:434)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

The hic files could be correctly displayed by Juicebox.

**Comment by sa501428** [comment]
Can you run this with --threads 1?
What version of the jar is this?
